

CREATE TABLE VEHICULO (PLACA int PRIMARY KEY NOT NULL,
MARCA varchar(20) NOT NULL,
MODELO varchar(20) NOT NULL,
ANO DECIMAL NOT NULL,
PRECIO  decimal(7, 2) NOT NULL,
N_MOTOR INTEGER NOT NULL,
N_SERIE INTEGER NOT NULL,
sys_start TIMESTAMP(12) GENERATED ALWAYS AS ROW BEGIN NOT NULL,
sys_end TIMESTAMP(12) GENERATED ALWAYS AS ROW END NOT NULL,
trans_start TIMESTAMP(12) GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
period system_time (sys_start, sys_end));


CREATE TABLE POLIZA (N_POLIZA int primary key NOT NULL,
TIPO INTEGER NOT NULL,
PRECIO  decimal(7, 2) NOT NULL,
N_MOTOR INTEGER NOT NULL,
N_SERIE INTEGER NOT NULL,
PLACA INTEGER NOT NULL,
sstart TIMESTAMP(12) GENERATED ALWAYS AS ROW BEGIN NOT NULL,
send TIMESTAMP(12) GENERATED ALWAYS AS ROW END NOT NULL,
PERIOD system_time(SSTART, SEND),
trans_start TIMESTAMP(12) GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
FOREIGN KEY(PLACA)REFERENCES VEHICULO(PLACA));

CREATE TABLE USUARIO (USER_ID int PRIMARY KEY NOT NULL,
NOMBRE varchar(20) NOT NULL,
DIRECCION varchar(20) NOT NULL,
N_POLIZA INTEGER NOT NULL,
BUS_start DATE NOT NULL,
BUS_end DATE NOT NULL,
period BUSINESS_TIME(BUS_start, BUS_end), 
FOREIGN KEY(N_POLIZA)REFERENCES POLIZA(N_POLIZA));

CREATE TABLE POLIZA_HISTORY LIKE POLIZA
ALTER TABLE POLIZA ADD VERSIONING USE HISTORY TABLE POLIZA_HISTORY



INSERT INTO VEHICULO (PLACA, MARCA, MODELO, ANO, PRECIO, N_MOTOR, N_SERIE) VALUES (23, 'vw', 'vocho', 1995, 5000, 2, 123)

INSERT INTO POLIZA (N_POLIZA, TIPO, PRECIO, N_MOTOR, N_SERIE, PLACA) VALUES (1234567890, 1, 50000, 2, 123, 23)

INSERT INTO USUARIO (USER_ID, NOMBRE, DIRECCION, N_POLIZA, BUS_START, BUS_END) VALUES (12345, 'EMILIO', 'DIRIXION', 1234567890, '2018-03-01', '2018-06-01')

UPDATE POLIZA SET PRECIO = 5000 WHERE n_poliza = 1234567890

SELECT * FROM USUARIO FOR BUSINESS_TIME AS OF '2018-03-01'
