CREATE TABLE VEHICULO (PLACA int PRIMARY KEY NOT NULL,
MARCA varchar(20) NOT NULL,
MODELO varchar(20) NOT NULL,
ANO DECIMAL NOT NULL,
PRECIO  decimal(7, 2) NOT NULL,
N_MOTOR INTEGER NOT NULL,
N_SERIE INTEGER NOT NULL,
sys_start TIMESTAMP(12) GENERATED ALWAYS AS ROW BEGIN NOT NULL,
sys_end TIMESTAMP(12) GENERATED ALWAYS AS ROW END NOT NULL,
trans_start TIMESTAMP(12) GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
period system_time (sys_start, sys_end));


CREATE TABLE POLIZA (N_POLIZA int NOT NULL,
TIPO INTEGER NOT NULL,
PRECIO  decimal(7, 2) NOT NULL,
N_MOTOR INTEGER NOT NULL,
N_SERIE INTEGER NOT NULL,
PLACA INTEGER NOT NULL,
CSTART DATE NOT NULL,
CEND DATE NOT NULL,
PERIOD BUSINESS_TIME(CSTART, CEND),
PRIMARY KEY(N_POLIZA, BUSINESS_TIME WITHOUT OVERLAPS),
FOREIGN KEY(PLACA)REFERENCES VEHICULO(PLACA));

CREATE TABLE USUARIO (USER_ID int PRIMARY KEY NOT NULL,
NOMBRE 
varchar(20) NOT NULL,
DIRECCION varchar(20) NOT NULL,
PO INT NOT NULL,
sys_start TIMESTAMP(12) GENERATED ALWAYS AS ROW BEGIN NOT NULL,
sys_end TIMESTAMP(12) GENERATED ALWAYS AS ROW END NOT NULL,
trans_start TIMESTAMP(12) GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
period system_time (sys_start, sys_end),
FOREIGN KEY(PO)REFERENCES POLIZA(N_POLIZA));